// <auto-generated />
namespace SAPOC.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableProductAddColumnSKU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableProductAddColumnSKU));
        
        string IMigrationMetadata.Id
        {
            get { return "201611221253053_TableProductAddColumnSKU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
